
import type { Employee, Project } from '@/shared/types';

// This file is autogenerated by the Vercel AI SDK, and is used to
// new types can be added to this file, but it should not be modified
// in any other way.

interface KpiData {
    newRequests: number;
    openQuotes: number;
    activeProjects: number;
    unplannedProjects: number;
    monthlyExpenses: number;
}

interface EmployeeStat {
    employee: Employee;
    totalHours: number;
    grossPay: number;
}

interface RecentActivity {
    project: Project;
    description: string;
    imageUrls: string[];
    date: string;
}

interface MonthlyRevenue {
    name: string;
    total: number;
}

export interface DashboardData {
    kpi: KpiData;
    employeeStats: EmployeeStat[];
    recentActivities: RecentActivity[];
    monthlyRevenue: MonthlyRevenue[];
}
