extend type Article {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Article", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Article`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Article.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Customer {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Customer", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Customer`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Customer.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Document {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Document", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Document`.`customer`. It must match the value of `Customer`.`id`. See `@ref` for how to customize it.
  """
  customerId: UUID! @fdc_generated(from: "Document.customer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Document`.`project`. It must match the value of `Project`.`id`. See `@ref` for how to customize it.
  """
  projectId: UUID @fdc_generated(from: "Document.project", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Document`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Document.user", purpose: IMPLICIT_REF_FIELD)
}
extend type DocumentLineItem {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "DocumentLineItem", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `DocumentLineItem`.`article`. It must match the value of `Article`.`id`. See `@ref` for how to customize it.
  """
  articleId: UUID @fdc_generated(from: "DocumentLineItem.article", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `DocumentLineItem`.`document`. It must match the value of `Document`.`id`. See `@ref` for how to customize it.
  """
  documentId: UUID! @fdc_generated(from: "DocumentLineItem.document", purpose: IMPLICIT_REF_FIELD)
}
extend type Project {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Project", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Project`.`customer`. It must match the value of `Customer`.`id`. See `@ref` for how to customize it.
  """
  customerId: UUID! @fdc_generated(from: "Project.customer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Project`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Project.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
